name = "nodematiclabs"
compatibility_date = "2024-09-30"
workers_dev = true
main = "site/main.js" # Ensure this points to the correct file

[site]
bucket = "./site" # Ensure this points to your static files directory
