name = "simple-cloudflare-worker"
compatibility_date = "2024-09-30"
workers_dev = true

[env.staging]
name = "simple-cloudflare-worker-staging" # Use a different name for staging deployment
route = "" # Set a route if deploying to a custom domain in staging

[env.production]
name = "simple-cloudflare-worker-prod" # Use the original or a different name for production
route = "" # Set a route if deploying to a custom domain in production
