name = "nodematiclabs"  # Base name for your Worker
compatibility_date = "2024-09-30" # Update this to the current date
workers_dev = true

# Define the Staging environment
[env.staging]
name = "nodematiclabs-staging" # Unique name for the staging environment
route = "" # Use this if you want to deploy to a custom domain; leave blank for workers.dev
# Optional: Add other environment-specific settings here

# Define the Production environment
[env.production]
name = "nodematiclabs-prod" # Unique name for the production environment
route = "" # Use this if you want to deploy to a custom domain; leave blank for workers.dev
# Optional: Add other environment-specific settings here
