name: Cloudflare Workers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Setup Node.js environment
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '18' # Use the latest stable version of Node.js

      # Deploy using the latest Wrangler
      - name: Deploy via Cloudflare Workers
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npm uninstall -g @cloudflare/wrangler # Uninstall old version if previously installed
          npm install -g wrangler # Install the latest Wrangler version (v2.x)
          wrangler publish
