name: Cloudflare Workers Deployment

# This workflow will run whenever there is a push or pull request on the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    # This job will run on the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true' # Ensures any submodules are checked out

      # Step 2: Set up Node.js environment
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '18' # Updated to a more recent Node.js version

      # Step 3: Deploy via Cloudflare Workers
      - name: Deploy via Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} # Ensure this secret is correctly set in GitHub Secrets
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }} # Ensure this secret is correctly set in GitHub Secrets
        run: |
          npm uninstall -g @cloudflare/wrangler # Uninstall old version if previously installed
          npm install -g wrangler # Install the latest Wrangler version (v2.x)
          wrangler deploy # Updated to use deploy instead of publish
